#
#Wed May 20 14:39:43 COT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized, \\n                     --test-type, \\n                     --no-sandbox, \\n                     --ignore-certificate-errors, \\n                     --disable-popup-blocking, \\n                     --disable-default-apps, \\n                     --disable-extensions-file-access-check, \\n                     --incognito, \\n                     --disable-infobars, \\n                     --disable-gpu, \\n                     --remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=true
browserName=chrome
